version: "4.0"

services:
#  product-service:
#    build: opentelemetry-spring-boot-svc1/
#    ports:
#      - "8080:8080"
#
#  price-service:
#    build: opentelemetry-spring-boot-svc2/
#    ports:
#      - "8081"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"

  collector:
    image: otel/opentelemetry-collector:0.72.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
    depends_on:
      - jaeger